[package]
name = "hasse-diagram"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
imageproc = "0.24.0"
image = "0.25.0"
ab_glyph = "0.2.23"
rand = "0.8.5"
dialoguer = "0.11.0"
